twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic    : cmd_vel_teleop
        timeout  : 0.5
        priority : 100        # teleop always overrides nav
      navigation:
        topic    : cmd_vel_nav
        timeout  : 0.5
        priority : 10         # Nav2 output, lower priority than teleop
